---
# GC5 N96 ORCA1 spinup analysis
name: ocean_alkalisation

# Run the single job analysis
do_analysis_timeseries: True 
# Download from mass:
do_mass_download: False

# master analysis suite
master_suites: kmf bgc alkalinity physics

clean: True

# Job ID's suites as named by Rose/Cylc
# •     u-bj141 - control
# •     u-bo540 - experiment 1, geoengineering to 2050
# •     u-bp104 - experiment 2, geoengineering to 2100
#
jobs:
    u-bj141:
        description: 'control'
        colour: black
        thickness: 0.7
        linestyle: '-'
        shifttime: 0.
        suite: kmf bgc alkalinity_norivalk physics
    u-bo540:
       description: 'experiment 1, geoengineering to 2050'
       colour: red 
       thickness: 2.0
       linestyle: '-'
       shifttime: 0.
       suite: kmf bgc alkalinity_norivalk physics
    u-bp104:
       description: 'experiment 2, geoengineering to 2100'
       colour: blue
       thickness: 2.0
       linestyle: '-'
       shifttime: 0.
       suite: kmf bgc alkalinity_norivalk physics





