---
# GC5 N96 ORCA1 spinup analysis
name: TerraFIRMA_SSP245_CMM

# Run the single job analysis
do_analysis_timeseries: True  

# Download from mass:
do_mass_download: False

# master analysis suite
master_suites: &keylists physics bgc kmf tfamoc #alkalinity physics


# Run without strick check (if True, breaks if job has no years.)
strict_file_check: False

# Output the figures as csv json files.
savejson: True

clean: True


jobs:


   # PI CONTROL
   u-cs495:
      description: 'PI-Control'
      label: 'PIcontrol'
      colour: 'blue' 
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      timerange: [1825, 2200]
      suite: *keylists
         



   u-cy623:
      description: 'interactive ice, started from picontrol yr 2277'
      label: 'Historical' 
      colour: 'maroon'
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      #timerange: [1800, 2050]
      suite: *keylists

   u-da914:
      description: 'interactive ice, started from picontrol yr 2197'
      label: None
      colour: 'red'
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      #timerange: [1800, 2050]
      suite: *keylists

   u-da916:
      description: 'interactive ice, started from picontrol yr 2237'
      label: None
#     label: 'SSP2-4.5' 
      colour: 'red'
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      #timerange: [1800, 2050]
      suite: *keylists

   u-da917:
      description: 'interactive ice, started from picontrol yr 2317'
      label: None
#     label: 'SSP2-4.5' 
      colour: 'red'
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      #timerange: [1800, 2050]
      suite: *keylists


#   u-dg308:
#      description: 'TF OS SSP245 cmm - High freq nemo, no CFC/SF6 output - ssp245 extension of u-da914'
##      label: 'Extension'
#      label: 'SSP2-4.5' 
#      colour: 'purple'
#      thickness: 1.2
#      linestyle: '-'
#      shifttime: 0.
#      #timerange: [1800, 2050]
#      suite: *keylists


   u-dg480:
      description: 'Interactive ice TF OS SSP245 cmm - High freq nemo, no CFC/SF6 output - ssp245 extension of u-cy623'
#      label: 'Extension'
      label: 'SSP2-4.5'
      colour: 'violet'
      thickness: 1.2
      linestyle: '-'
      shifttime: 0.
      #timerange: [1800, 2050]
      suite: *keylists


 #  u-dg508:
 #     description: 'TF OS SSP245 cmm - High freq nemo, no CFC/SF6 output from 2030 onwards - ssp245 extension of u-da916'
 #     label: None
##     label: 'SSP2-4.5' 
 #     colour: 'purple'
 #     thickness: 1.2
 #     linestyle: '-'
 #     shifttime: 0.
 #     #timerange: [1800, 2050]
 #     suite: *keylists


#   u-dg327:
#      description: 'Revised SSP236. '
#      label: None
##     label: 'SSP2-4.5'
#      colour: 'green'
#      thickness: 1.2
#      linestyle: '-'
#      shifttime: 0.
#      #timerange: [1800, 2050]
#      suite: *keylists

#   u-dg509:
#      description: 'TF OS SSP245 cmm - High freq nemo, no CFC/SF6 output from 2030 onwards - ssp245 extension of u-da917'
#      label: None
#      label: 'SSP2-4.5' 
#      colour: 'purple'
#      thickness: 1.2
#      linestyle: '-'
#      shifttime: 0.
#      #timerange: [1800, 2050]
#      suite: *keylists

