---
# GC5 N96 ORCA1 spinup analysis
name: TerraFIRMA_overshoot_pi_2022

# Run the single job analysis
do_analysis_timeseries: True 
# Download from mass:
do_mass_download: False

# master analysis suite
master_suites: physics bgc #alkalinity physics kmf1

clean: True

#           u-cp530: CO2 conc mode, interactive ice but fixed ice geometry (red)
#           u-cs495: CO2 emission mode, interactive ice but fixed ice geometry (green) 
#           u-cp345: CO2 conc mode, interactive ice and interactive (variable) ice geometry (blue)

# Job ID's suites as named by Rose/Cylc
# •     u-co094 - no alk added
# •     u-cp800 - alk add at surface
# •     u-cp799 - alk added at bathy - or 100m (if bathy deeper)
# •     u-cn857 - alk added at bathy - or 200m (if bathy deeper)
#
jobs:

    u-by230:
       description: 'UKESM1.1 piControl (abridged)'
       colour: 'black'
       thickness: 0.6
       linestyle: '-'
       shifttime: 0.
       timerange: [1900, 2000]
       suite: physics bgc #alkalinity physics


    u-cs568:
       description: 'TF overshoot piControl variant #1'
       colour: red  
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: physics bgc #alkalinity physics

    u-cp530: 
       description: 'TF overshoot piControl variant #4 conc mode, interactive ice but fixed ice geometry'
       colour: purple
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: physics bgc #alkalinity physics


    u-cp345:
       description: 'TF overshoot piControl variant #2 CO2 conc mode, interactive ice and interactive (variable) ice geometry'
       colour: blue
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: physics bgc #alkalinity physics

    u-cs495:
       description: 'TF overshoot piControl variant #3 CO2 emission mode, interactive ice but fixed ice geometry'
       colour: green
       thickness: 1.7
       linestyle: '-'
       shifttime: 0.
       suite: physics  bgc #alkalinity physics kmf




