---
name: TerraFIRMA_overshoot_stables

# Run the single job analysis
do_analysis_timeseries: True

# Download from mass:
do_mass_download: False

# master analysis suite
master_suites: &keylists physics bgc kmf tfamoc #alkalinity physics


# Run without strick check (if True, breaks if job has no years.)
strict_file_check: False

# Output the figures as csv json files.
savejson: True

clean: True

jobs:
   u-cs495:
       description: 'PI-Control'
       label: 'PIcontrol'
       colour: 'blue'
       thickness: 1.2
       linestyle: '-'
       shifttime: -2094
       timerange: [-50., 400.]
       suite: *keylists

# u-cz826:
   #    description: 'like cx209 but static ice sheet geometry 8GtC/yr #5'
   #    label: 'Ramp-up #5'
   #    colour: 'black'
   #    thickness: 1.2
   #    linestyle: '-'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists

   # 1.5k Stabilisation
   u-cy837:
      description: '1.5K Stabilisation from u-cx209 (#1)'
      label: '1.5K Stable' # #1'
      colour: 'lawngreen'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1919.
      #timerange: [1800, 2050]
      suite: *keylists   
   u-cz834:
      description: '1.5K Stabilisation from u-cw988 (#2)'
      label: None #Stable #2'
      colour: 'lawngreen'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1931.
      #timerange: [1800, 2050]
      suite: *keylists
   u-da087:
      description: '1.5K Stabilisation from u-cw989 (#3)'
      label: None #'Stable #3'
      colour: 'lawngreen' 
      thickness: 1.2
      linestyle: '-'
      shifttime: -1922.
      #timerange: [1800, 2050]
      suite: *keylists
           
    # 2k Stabilisation
   u-cy838:
      description: '2.0K Stabilisation from u-cx209 (#1)'
      label: '2K Stable' # #1'
      colour: 'goldenrod'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1944.
      #timerange: [1800, 2050]
      suite: *keylists   

   u-cz855:
      description: '2.0K Stabilisation from cw988 (#2)'
      label: None #'2K Stable #2'
      colour: 'goldenrod'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1956.
      #timerange: [1800, 2050]
      suite: *keylists

   u-da266:
      description: '2.0K Stabilisation from cw988 (#3)'
      label: None #'2K Stable #3'
      colour: 'goldenrod'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1947
      #timerange: [1800, 2050]
      suite: *keylists
           
    # 2.5k Stabilisation
   u-cz374:
      description: '2.5K Stabilisation from u-cx209 (#1)'
      label: '2.5K Stable' # #1'
      colour: 'orange'
      thickness: 1.2
      linestyle: '-'
      shifttime: -1970.
      #timerange: [1800, 2050]
      suite: *keylists   
   u-cz859:
      description: '2.5K Stabilisation from cw988 (#2)'
      label: None #'2.5K Stable #2'
      colour: 'orange' 
      thickness: 1.2
      linestyle: '-'
      shifttime: -1979.
      #timerange: [1800, 2050]
      suite: *keylists


    # 3.0K Stabilisations
   u-cz375:
      description: '3.0K Stabilisation from u-cx209 (#1)'
      label: '3K Stable' # #1'
      colour: 'red'     #
      thickness: 1.2
      linestyle: '-'
      shifttime: -1992.
      #timerange: [1800, 2050]
      suite: *keylists          

   u-db587:
      description: '3.0K Stabilisation from u-cx209 (#2)'
      label: None #'3K Stable #2'
      colour: 'red'     #
      thickness: 1.2
      linestyle: '-'
      shifttime: -2004.
      #timerange: [1800, 2050]
      suite: *keylists  

   u-db597:
      description: '3.0K Stabilisation from u-cx209 (#3)'
      label: None #'3K Stable #3'
      colour: 'red'     #
      thickness: 1.2
      linestyle: '-'
      shifttime: -1994.
      #timerange: [1800, 2050]
      suite: *keylists         #       

    # 4k  Stabilisations
   u-cz376:
      description: '4.0K Stabilisation from u-cx209 (#1)'
      label: '4K Stable' # #1'
      colour: 'sienna'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2044.
      #timerange: [1800, 2050]
      suite: *keylists  
   u-db723:
      description: '4.0K Stabilisation from u-cw988 (#2)'
      label: None #'4K Stable #2'
      colour: 'sienna'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2049.
      #timerange: [1800, 2050]
      suite: *keylists      
   u-db733:
      description: '4.0K Stabilisation from u-cw989 (#3)'
      label: None #'4K Stable #3'
      colour: 'sienna'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2036.
      #timerange: [1800, 2050]
      suite: *keylists      

    # 5k & 6K  Stabilisations
   u-cz377:
      description: '5.0K Stabilisation from u-cx209 (#1)'
      label: '5K Stable'
      colour: 'maroon'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2082.
      #timerange: [1800, 2050]
      suite: *keylists 
   u-db731:
      description: '5.0K Stabilisation from u-cw988 (#2)'
      label: None #'5K Stable #2'
      colour: 'maroon'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2095.
      #timerange: [1800, 2050]
      suite: *keylists 
   u-dc324:
      description: '5.0K Stabilisation from u-cw989 (#3)'
      label: None #'5K Stable #3'
      colour: 'maroon'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2084.
      #timerange: [1800, 2050]
      suite: *keylists 

   u-cz378:
      description: '6.0K Stabilisation from u-cx209 (#1)'
      label: '6K Stable'
      colour: 'indigo'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2137.
      #timerange: [1800, 2050]
      suite: *keylists 

   #  # Ramp downs
   # u-cz944:
   #    description: 'Ramp down from cy838 (- 2.0K Stabilisation from u-cx209) (#1)'
   #    label: '2K Rampdown #1'
   #    colour: 'goldenrod'
   #    thickness: 1.2
   #    linestyle: ':' 
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists   
   # u-da800:
   #    description: 'Ramp down from cy838 (- 2.0K Stabilisation from u-cx209) (#1)'
   #    label: '2K Rampdown #1'
   #    colour: 'goldenrod'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists   

   # u-da697:
   #    description: '1.5K Rampdown from u-cx209 (#1)'
   #    label: '1.5K Rampdown #1'
   #    colour: 'lawngreen'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists

   # u-da892:
   #    description: '4.K Rampdown (#1)'
   #    label: '4.K Rampdown #1'
   #    colour: 'sienna'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-db223:
   #    description: '3.K Rampdown (#1)'
   #    label: '3.K Rampdown #1'
   #    colour: 'red'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-dc051:
   #    description: 'Rampdown from yr 50 of 1.5 stab #1, -4GtC/yr (#1)'
   #    label: '1.5K Rampdown #1'
   #    colour: 'lawngreen'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists  

   # u-dc052:
   #    description: 'Rampdown from yr 200 of 1.5deg, -4GtC/yr (#1)'
   #    label: '1.5K Rampdown #1'
   #    colour: 'lawngreen'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0
   #    #timerange: [1800, 2050]
   #    suite: *keylists  

   # u-dc248:
   #    description: '1.5K Rampdown -4GtC/yr, (#1)'
   #    label: '1.5K Rampdown #1'
   #    colour: 'lawngreen'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-dc249:
   #    description: '3.K Rampdown -4GtC/yr, 200 years, (#1)'
   #    label: '3.K Rampdown #1'
   #    colour: 'red'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-dc251:
   #    description: '5K Rampdown -8GtC/yr, 50 years, (#1)'
   #    label: '5K Rampdown #1'
   #    colour: 'maroon'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-db956:
   #    description: '1.5K Rampdown -8GtC/yr, 0 years, (#1)'
   #    label: '1.5K Rampdown #1'
   #    colour: 'lawngreen'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    suite: *keylists

   # u-dc032:
   #    description: 'ramp-down from yr 50 of 3.0 stab #1, free ice, -4GtC/yr (#1)'
   #    label: '3K Rampdown #1'
   #    colour: 'red'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists
   # u-dc123:
   #    description: 'ramp-down from yr 50 of 4.0 stab #1, free ice, -4GtC/yr (#1)'
   #    label: '4K Rampdown #1'
   #    colour: 'sienna'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists
   # u-dc130:
   #    description: 'ramp-down from yr 50 of 5.0 stab #1, free ice, -4GtC/yr (#1)'
   #    label: '5K Rampdown #1'
   #    colour: 'maroon'
   #    thickness: 1.2
   #    linestyle: ':'
   #    shifttime: 0.
   #    #timerange: [1800, 2050]
   #    suite: *keylists

   # Ramp down stables.
   u-dc163:
      description: 'Stable post ramp-down (#1)'
      label: None #'Stab Rampdown #1'
      colour: 'lawngreen'
      thickness: 1.2
      linestyle: '-'
      shifttime: -2019.
      #timerange: [1800, 2050]
      suite: *keylists      
