name: Test on Push on Linux64

on:
  push:

jobs:
  linux:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.12"]
      fail-fast: false
    name: Linux Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: bgcval2
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: "latest"
          use-mamba: true
      - shell: bash -l {0}
        run: conda --version
      - shell: bash -l {0}
        run: python -V
      - shell: bash -l {0}
        run: pip install -e .[develop]
      - shell: bash -l {0}
        run: |
          analysis_compare --help
          analysis_level3_amoc --help
          analysis_level3_dms --help
          analysis_level3_omz --help
          analysis_level3_sameYear --help
          analysis_p2p --help
          analysis_timeseries --help
          bgcval2_make_report --help
          download_from_mass --help 
      - shell: bash -l {0}
        run: |
          echo "hostname=github" >> $GITHUB_ENV
          pytest
      - shell: bash -l {0}
        run: sphinx-build -Ea doc doc/build
